networks:
  romeo_pleno_test_network:
    name: romeo_pleno_test_network

services:
  romeo_pleno_test_mongo:
    image: mongo:4.4.6
    container_name: romeo_pleno_test_mongo
    restart: always
    networks:
      - romeo_pleno_test_network
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_COLLECTION}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  romeo_pleno_test_redis:
    image: redis
    container_name: romeo_pleno_test_redis
    restart: always
    networks:
      - romeo_pleno_test_network
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
